"""empty message

Revision ID: c501d3e9f45a
Revises: 
Create Date: 2018-02-25 19:11:13.570773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c501d3e9f45a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coin_current_data',
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('coin_rank', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('price_btc', sa.Float(), nullable=True),
    sa.Column('volume_usd_24h', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('available_supply', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('max_supply', sa.Float(), nullable=True),
    sa.Column('percentage_change_1h', sa.Float(), nullable=True),
    sa.Column('percentage_change_24h', sa.Float(), nullable=True),
    sa.Column('percentage_change_7d', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_coin_current_data_name'), 'coin_current_data', ['name'], unique=False)
    op.create_index(op.f('ix_coin_current_data_symbol'), 'coin_current_data', ['symbol'], unique=False)
    op.create_table('coin_daily_data',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('coin_rank', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('price_btc', sa.Float(), nullable=True),
    sa.Column('volume_usd_24h', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('available_supply', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('max_supply', sa.Float(), nullable=True),
    sa.Column('percentage_change_1h', sa.Float(), nullable=True),
    sa.Column('percentage_change_24h', sa.Float(), nullable=True),
    sa.Column('percentage_change_7d', sa.Float(), nullable=True),
    sa.Column('update_date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_coin_daily_data_name'), 'coin_daily_data', ['name'], unique=False)
    op.create_index(op.f('ix_coin_daily_data_rec_id'), 'coin_daily_data', ['rec_id'], unique=False)
    op.create_index(op.f('ix_coin_daily_data_symbol'), 'coin_daily_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_coin_daily_data_update_date_time'), 'coin_daily_data', ['update_date_time'], unique=False)
    op.create_table('coin_historical_data',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('open_usd', sa.Float(), nullable=True),
    sa.Column('high_usd', sa.Float(), nullable=True),
    sa.Column('low_usd', sa.Float(), nullable=True),
    sa.Column('close_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_coin_historical_data_data_date'), 'coin_historical_data', ['data_date'], unique=False)
    op.create_index(op.f('ix_coin_historical_data_name'), 'coin_historical_data', ['name'], unique=False)
    op.create_index(op.f('ix_coin_historical_data_rec_id'), 'coin_historical_data', ['rec_id'], unique=False)
    op.create_index(op.f('ix_coin_historical_data_symbol'), 'coin_historical_data', ['symbol'], unique=False)
    op.create_table('coin_master',
    sa.Column('symbol', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('details', sa.String(length=512), nullable=True),
    sa.Column('icon_url', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_index(op.f('ix_coin_master_name'), 'coin_master', ['name'], unique=False)
    op.create_index(op.f('ix_coin_master_symbol'), 'coin_master', ['symbol'], unique=False)
    op.create_table('coin_monthly_data',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('coin_rank', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('price_btc', sa.Float(), nullable=True),
    sa.Column('volume_usd_24h', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('available_supply', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('max_supply', sa.Float(), nullable=True),
    sa.Column('percentage_change_1h', sa.Float(), nullable=True),
    sa.Column('percentage_change_24h', sa.Float(), nullable=True),
    sa.Column('percentage_change_7d', sa.Float(), nullable=True),
    sa.Column('update_date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_coin_monthly_data_name'), 'coin_monthly_data', ['name'], unique=False)
    op.create_index(op.f('ix_coin_monthly_data_rec_id'), 'coin_monthly_data', ['rec_id'], unique=False)
    op.create_index(op.f('ix_coin_monthly_data_symbol'), 'coin_monthly_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_coin_monthly_data_update_date_time'), 'coin_monthly_data', ['update_date_time'], unique=False)
    op.create_table('coin_weekly_data',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('coin_rank', sa.Integer(), nullable=True),
    sa.Column('price_usd', sa.Float(), nullable=True),
    sa.Column('price_btc', sa.Float(), nullable=True),
    sa.Column('volume_usd_24h', sa.Float(), nullable=True),
    sa.Column('market_cap_usd', sa.Float(), nullable=True),
    sa.Column('available_supply', sa.Float(), nullable=True),
    sa.Column('total_supply', sa.Float(), nullable=True),
    sa.Column('max_supply', sa.Float(), nullable=True),
    sa.Column('percentage_change_1h', sa.Float(), nullable=True),
    sa.Column('percentage_change_24h', sa.Float(), nullable=True),
    sa.Column('percentage_change_7d', sa.Float(), nullable=True),
    sa.Column('update_date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_coin_weekly_data_name'), 'coin_weekly_data', ['name'], unique=False)
    op.create_index(op.f('ix_coin_weekly_data_rec_id'), 'coin_weekly_data', ['rec_id'], unique=False)
    op.create_index(op.f('ix_coin_weekly_data_symbol'), 'coin_weekly_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_coin_weekly_data_update_date_time'), 'coin_weekly_data', ['update_date_time'], unique=False)
    op.create_table('cryptocompare_1hour_chart',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('rate_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_1hour_chart_data_date'), 'cryptocompare_1hour_chart', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_1hour_chart_rec_id'), 'cryptocompare_1hour_chart', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_1hour_chart_symbol'), 'cryptocompare_1hour_chart', ['symbol'], unique=False)
    op.create_table('cryptocompare_1month_chart',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('rate_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_1month_chart_data_date'), 'cryptocompare_1month_chart', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_1month_chart_rec_id'), 'cryptocompare_1month_chart', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_1month_chart_symbol'), 'cryptocompare_1month_chart', ['symbol'], unique=False)
    op.create_table('cryptocompare_1week_chart',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('rate_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_1week_chart_data_date'), 'cryptocompare_1week_chart', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_1week_chart_rec_id'), 'cryptocompare_1week_chart', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_1week_chart_symbol'), 'cryptocompare_1week_chart', ['symbol'], unique=False)
    op.create_table('cryptocompare_24hour_chart',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('rate_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_24hour_chart_data_date'), 'cryptocompare_24hour_chart', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_24hour_chart_rec_id'), 'cryptocompare_24hour_chart', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_24hour_chart_symbol'), 'cryptocompare_24hour_chart', ['symbol'], unique=False)
    op.create_table('cryptocompare_6month_chart',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('rate_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_6month_chart_data_date'), 'cryptocompare_6month_chart', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_6month_chart_rec_id'), 'cryptocompare_6month_chart', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_6month_chart_symbol'), 'cryptocompare_6month_chart', ['symbol'], unique=False)
    op.create_table('cryptocompare_daily_history',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('open_usd', sa.Float(), nullable=True),
    sa.Column('high_usd', sa.Float(), nullable=True),
    sa.Column('low_usd', sa.Float(), nullable=True),
    sa.Column('close_usd', sa.Float(), nullable=True),
    sa.Column('volume_from', sa.Float(), nullable=True),
    sa.Column('volume_to', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_daily_history_data_date'), 'cryptocompare_daily_history', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_daily_history_name'), 'cryptocompare_daily_history', ['name'], unique=False)
    op.create_index(op.f('ix_cryptocompare_daily_history_rec_id'), 'cryptocompare_daily_history', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_daily_history_symbol'), 'cryptocompare_daily_history', ['symbol'], unique=False)
    op.create_table('cryptocompare_hourly_history',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('open_usd', sa.Float(), nullable=True),
    sa.Column('high_usd', sa.Float(), nullable=True),
    sa.Column('low_usd', sa.Float(), nullable=True),
    sa.Column('close_usd', sa.Float(), nullable=True),
    sa.Column('volume_from', sa.Float(), nullable=True),
    sa.Column('volume_to', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_hourly_history_data_date'), 'cryptocompare_hourly_history', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_hourly_history_name'), 'cryptocompare_hourly_history', ['name'], unique=False)
    op.create_index(op.f('ix_cryptocompare_hourly_history_rec_id'), 'cryptocompare_hourly_history', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_hourly_history_symbol'), 'cryptocompare_hourly_history', ['symbol'], unique=False)
    op.create_table('cryptocompare_minute_history',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('open_usd', sa.Float(), nullable=True),
    sa.Column('high_usd', sa.Float(), nullable=True),
    sa.Column('low_usd', sa.Float(), nullable=True),
    sa.Column('close_usd', sa.Float(), nullable=True),
    sa.Column('volume_from', sa.Float(), nullable=True),
    sa.Column('volume_to', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_minute_history_data_date'), 'cryptocompare_minute_history', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_minute_history_name'), 'cryptocompare_minute_history', ['name'], unique=False)
    op.create_index(op.f('ix_cryptocompare_minute_history_rec_id'), 'cryptocompare_minute_history', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_minute_history_symbol'), 'cryptocompare_minute_history', ['symbol'], unique=False)
    op.create_table('cryptocompare_nyear_chart',
    sa.Column('rec_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=30), nullable=True),
    sa.Column('data_date', sa.DateTime(), nullable=True),
    sa.Column('rate_usd', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('rec_id')
    )
    op.create_index(op.f('ix_cryptocompare_nyear_chart_data_date'), 'cryptocompare_nyear_chart', ['data_date'], unique=False)
    op.create_index(op.f('ix_cryptocompare_nyear_chart_rec_id'), 'cryptocompare_nyear_chart', ['rec_id'], unique=False)
    op.create_index(op.f('ix_cryptocompare_nyear_chart_symbol'), 'cryptocompare_nyear_chart', ['symbol'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    op.create_table('portfolio_items',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('folio_id', sa.Integer(), nullable=True),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('coin_symbol', sa.String(length=30), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('purchase_price', sa.Float(), nullable=True),
    sa.Column('purchase_fees', sa.Float(), nullable=True),
    sa.Column('broker', sa.String(length=150), nullable=True),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('sold_at_price', sa.Float(), nullable=True),
    sa.Column('sold_fees', sa.Float(), nullable=True),
    sa.Column('sold_on_date', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.String(length=700), nullable=True),
    sa.ForeignKeyConstraint(['coin_symbol'], ['coin_master.symbol'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_portfolio_items_item_id'), 'portfolio_items', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_items_item_id'), table_name='portfolio_items')
    op.drop_table('portfolio_items')
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_cryptocompare_nyear_chart_symbol'), table_name='cryptocompare_nyear_chart')
    op.drop_index(op.f('ix_cryptocompare_nyear_chart_rec_id'), table_name='cryptocompare_nyear_chart')
    op.drop_index(op.f('ix_cryptocompare_nyear_chart_data_date'), table_name='cryptocompare_nyear_chart')
    op.drop_table('cryptocompare_nyear_chart')
    op.drop_index(op.f('ix_cryptocompare_minute_history_symbol'), table_name='cryptocompare_minute_history')
    op.drop_index(op.f('ix_cryptocompare_minute_history_rec_id'), table_name='cryptocompare_minute_history')
    op.drop_index(op.f('ix_cryptocompare_minute_history_name'), table_name='cryptocompare_minute_history')
    op.drop_index(op.f('ix_cryptocompare_minute_history_data_date'), table_name='cryptocompare_minute_history')
    op.drop_table('cryptocompare_minute_history')
    op.drop_index(op.f('ix_cryptocompare_hourly_history_symbol'), table_name='cryptocompare_hourly_history')
    op.drop_index(op.f('ix_cryptocompare_hourly_history_rec_id'), table_name='cryptocompare_hourly_history')
    op.drop_index(op.f('ix_cryptocompare_hourly_history_name'), table_name='cryptocompare_hourly_history')
    op.drop_index(op.f('ix_cryptocompare_hourly_history_data_date'), table_name='cryptocompare_hourly_history')
    op.drop_table('cryptocompare_hourly_history')
    op.drop_index(op.f('ix_cryptocompare_daily_history_symbol'), table_name='cryptocompare_daily_history')
    op.drop_index(op.f('ix_cryptocompare_daily_history_rec_id'), table_name='cryptocompare_daily_history')
    op.drop_index(op.f('ix_cryptocompare_daily_history_name'), table_name='cryptocompare_daily_history')
    op.drop_index(op.f('ix_cryptocompare_daily_history_data_date'), table_name='cryptocompare_daily_history')
    op.drop_table('cryptocompare_daily_history')
    op.drop_index(op.f('ix_cryptocompare_6month_chart_symbol'), table_name='cryptocompare_6month_chart')
    op.drop_index(op.f('ix_cryptocompare_6month_chart_rec_id'), table_name='cryptocompare_6month_chart')
    op.drop_index(op.f('ix_cryptocompare_6month_chart_data_date'), table_name='cryptocompare_6month_chart')
    op.drop_table('cryptocompare_6month_chart')
    op.drop_index(op.f('ix_cryptocompare_24hour_chart_symbol'), table_name='cryptocompare_24hour_chart')
    op.drop_index(op.f('ix_cryptocompare_24hour_chart_rec_id'), table_name='cryptocompare_24hour_chart')
    op.drop_index(op.f('ix_cryptocompare_24hour_chart_data_date'), table_name='cryptocompare_24hour_chart')
    op.drop_table('cryptocompare_24hour_chart')
    op.drop_index(op.f('ix_cryptocompare_1week_chart_symbol'), table_name='cryptocompare_1week_chart')
    op.drop_index(op.f('ix_cryptocompare_1week_chart_rec_id'), table_name='cryptocompare_1week_chart')
    op.drop_index(op.f('ix_cryptocompare_1week_chart_data_date'), table_name='cryptocompare_1week_chart')
    op.drop_table('cryptocompare_1week_chart')
    op.drop_index(op.f('ix_cryptocompare_1month_chart_symbol'), table_name='cryptocompare_1month_chart')
    op.drop_index(op.f('ix_cryptocompare_1month_chart_rec_id'), table_name='cryptocompare_1month_chart')
    op.drop_index(op.f('ix_cryptocompare_1month_chart_data_date'), table_name='cryptocompare_1month_chart')
    op.drop_table('cryptocompare_1month_chart')
    op.drop_index(op.f('ix_cryptocompare_1hour_chart_symbol'), table_name='cryptocompare_1hour_chart')
    op.drop_index(op.f('ix_cryptocompare_1hour_chart_rec_id'), table_name='cryptocompare_1hour_chart')
    op.drop_index(op.f('ix_cryptocompare_1hour_chart_data_date'), table_name='cryptocompare_1hour_chart')
    op.drop_table('cryptocompare_1hour_chart')
    op.drop_index(op.f('ix_coin_weekly_data_update_date_time'), table_name='coin_weekly_data')
    op.drop_index(op.f('ix_coin_weekly_data_symbol'), table_name='coin_weekly_data')
    op.drop_index(op.f('ix_coin_weekly_data_rec_id'), table_name='coin_weekly_data')
    op.drop_index(op.f('ix_coin_weekly_data_name'), table_name='coin_weekly_data')
    op.drop_table('coin_weekly_data')
    op.drop_index(op.f('ix_coin_monthly_data_update_date_time'), table_name='coin_monthly_data')
    op.drop_index(op.f('ix_coin_monthly_data_symbol'), table_name='coin_monthly_data')
    op.drop_index(op.f('ix_coin_monthly_data_rec_id'), table_name='coin_monthly_data')
    op.drop_index(op.f('ix_coin_monthly_data_name'), table_name='coin_monthly_data')
    op.drop_table('coin_monthly_data')
    op.drop_index(op.f('ix_coin_master_symbol'), table_name='coin_master')
    op.drop_index(op.f('ix_coin_master_name'), table_name='coin_master')
    op.drop_table('coin_master')
    op.drop_index(op.f('ix_coin_historical_data_symbol'), table_name='coin_historical_data')
    op.drop_index(op.f('ix_coin_historical_data_rec_id'), table_name='coin_historical_data')
    op.drop_index(op.f('ix_coin_historical_data_name'), table_name='coin_historical_data')
    op.drop_index(op.f('ix_coin_historical_data_data_date'), table_name='coin_historical_data')
    op.drop_table('coin_historical_data')
    op.drop_index(op.f('ix_coin_daily_data_update_date_time'), table_name='coin_daily_data')
    op.drop_index(op.f('ix_coin_daily_data_symbol'), table_name='coin_daily_data')
    op.drop_index(op.f('ix_coin_daily_data_rec_id'), table_name='coin_daily_data')
    op.drop_index(op.f('ix_coin_daily_data_name'), table_name='coin_daily_data')
    op.drop_table('coin_daily_data')
    op.drop_index(op.f('ix_coin_current_data_symbol'), table_name='coin_current_data')
    op.drop_index(op.f('ix_coin_current_data_name'), table_name='coin_current_data')
    op.drop_table('coin_current_data')
    # ### end Alembic commands ###
